#!/usr/bin/env bash
# Used as so: ./1-world_wide_web <domain> <subdomain>
#Shows info of sub domain

my_domain () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  my_domain "$1" "www"
  my_domain "$1" "lb-01"
  my_domain "$1" "web-01"
  my_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  my_domain "$1" "$2"
fi
