#!/usr/bin/env bash
# Shows the time for 12 horus and 59 minutes.
# Shows hours from 0 to 12
# Shows minutes from 1 to 59

time=0

while [ $time -le 12 ]
do
  echo "Hour: $time"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( time++ ))
done
